// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as BookingImport } from "./routes/booking";
import { Route as FacilityImport } from "./routes/facility";
import { Route as HomeImport } from "./routes/home";
import { Route as LoginImport } from "./routes/login";
import { Route as LogoutImport } from "./routes/logout";
import { Route as RegisterImport } from "./routes/register";
import { Route as FacilitiesImport } from "./routes/facilities";
import { Route as DashboardImport } from "./routes/dashboard/dashboard";
import { Route as DashboardProfileImport } from "./routes/dashboard/profile";
import { Route as DashboardFacilitiesImport } from "./routes/dashboard/facilities";
import { Route as DashboardBookingsImport } from "./routes/dashboard/bookings";
import { Route as DashboardReportsImport } from "./routes/dashboard/reports";
import { Route as ExampleImport } from "./routes/example";

// Create/Update Routes

const ExampleRoute = ExampleImport.update({
  id: "/example",
  path: "/example",
  getParentRoute: () => rootRoute,
});

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
});

const BookingRoute = BookingImport.update({
  id: "/booking",
  path: "/booking",
  getParentRoute: () => rootRoute,
});

const FacilityRoute = FacilityImport.update({
  id: "/facility",
  path: "/facility",
  getParentRoute: () => rootRoute,
});

const HomeRoute = HomeImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRoute,
});

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
});

const LogoutRoute = LogoutImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRoute,
});

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
});

const FacilitiesRoute = FacilitiesImport.update({
  id: "/facilities",
  path: "/facilities",
  getParentRoute: () => rootRoute,
});

const DashboardRoute = DashboardImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRoute,
});

const DashboardProfileRoute = DashboardProfileImport.update({
  id: "/dashboard/profile",
  path: "/dashboard/profile",
  getParentRoute: () => rootRoute,
});

const DashboardFacilitiesRoute = DashboardFacilitiesImport.update({
  id: "/dashboard/facilities",
  path: "/dashboard/facilities",
  getParentRoute: () => rootRoute,
});

const DashboardBookingsRoute = DashboardBookingsImport.update({
  id: "/dashboard/bookings",
  path: "/dashboard/bookings",
  getParentRoute: () => rootRoute,
});

const DashboardReportsRoute = DashboardReportsImport.update({
  id: "/dashboard/reports",
  path: "/dashboard/reports",
  getParentRoute: () => rootRoute,
});

// Create and export the route tree
const rootRouteChildren = {
  IndexRoute,
  BookingRoute,
  FacilityRoute,
  HomeRoute,
  LoginRoute,
  LogoutRoute,
  RegisterRoute,
  FacilitiesRoute,
  DashboardRoute,
  DashboardProfileRoute,
  DashboardFacilitiesRoute,
  DashboardBookingsRoute,
  DashboardReportsRoute,
  ExampleRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();

export const routeManifest = {
  "/": {
    filePath: "routes/index.jsx",
    parent: "/",
    children: [],
  },
  "/example": {
    filePath: "routes/example.jsx",
    parent: "/",
    children: [],
  },
  "/login": {
    filePath: "routes/login.jsx",
    parent: "/",
    children: [],
  },
  "/register": {
    filePath: "routes/register.jsx",
    parent: "/",
    children: [],
  },
  "/dashboard": {
    filePath: "routes/dashboard.jsx",
    parent: "/",
    children: [
      "/dashboard/profile",
      "/dashboard/facilities",
      "/dashboard/bookings",
      "/dashboard/reports",
    ],
  },
  "/dashboard/profile": {
    filePath: "routes/dashboard/profile.jsx",
    parent: "/dashboard",
    children: [],
  },
  "/dashboard/facilities": {
    filePath: "routes/dashboard/facilities.jsx",
    parent: "/dashboard",
    children: [],
  },
  "/dashboard/bookings": {
    filePath: "routes/dashboard/bookings.jsx",
    parent: "/dashboard",
    children: [],
  },
  "/dashboard/reports": {
    filePath: "routes/dashboard/reports.jsx",
    parent: "/dashboard",
    children: [],
  },
};

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/booking",
        "/facility",
        "/home",
        "/login",
        "/logout",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/booking": {
      "filePath": "booking.jsx"
    },
    "/facility": {
      "filePath": "facility.jsx"
    },
    "/home": {
      "filePath": "home.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/logout": {
      "filePath": "logout.jsx"
    },
    "/register": {
      "filePath": "register.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
