// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as indexRoute } from "./routes/index";
import { Route as RegisterImport } from "./routes/register";
import { Route as LogoutImport } from "./routes/logout";
import { Route as LoginImport } from "./routes/login";
import { Route as dashboardRoute } from "./routes/dashboard";
import { Route as dashboardIndexRoute } from "./routes/dashboard/index";
import { Route as dashboardFacilitiesRoute } from "./routes/dashboard/facilities";
import { Route as dashboardProfileRoute } from "./routes/dashboard/profile";

// Configure the routes

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
});

const LogoutRoute = LogoutImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRoute,
});

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
});

Object.assign(indexRoute.options, {
  path: "/",
  getParentRoute: () => rootRoute,
});

Object.assign(dashboardRoute.options, {
  path: "/dashboard",
  getParentRoute: () => rootRoute,
});

Object.assign(dashboardIndexRoute.options, {
  path: "/",
  getParentRoute: () => dashboardRoute,
});

Object.assign(dashboardFacilitiesRoute.options, {
  path: "/facilities",
  getParentRoute: () => dashboardRoute,
});

Object.assign(dashboardProfileRoute.options, {
  path: "/profile",
  getParentRoute: () => dashboardRoute,
});

// Create and export the route tree
export const routeTree = rootRoute.addChildren([
  indexRoute,
  dashboardRoute.addChildren([
    RegisterRoute,
    LogoutRoute,
    LoginRoute,
    dashboardIndexRoute,
    dashboardFacilitiesRoute,
    dashboardProfileRoute,
  ]),
]);

export const routeManifest = {
  "/": {
    filePath: "routes/index.jsx",
    parent: "/",
    children: [],
  },
  "/login": {
    filePath: "routes/login.jsx",
    parent: "/",
    children: [],
  },
  "/register": {
    filePath: "routes/register.jsx",
    parent: "/",
    children: [],
  },
  "/logout": {
    filePath: "routes/logout.jsx",
    parent: "/",
    children: [],
  },
};

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/booking",
        "/facility",
        "/home",
        "/login",
        "/logout",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/booking": {
      "filePath": "booking.jsx"
    },
    "/facility": {
      "filePath": "facility.jsx"
    },
    "/home": {
      "filePath": "home.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/logout": {
      "filePath": "logout.jsx"
    },
    "/register": {
      "filePath": "register.jsx"
    },
    "/dashboard": {
      "filePath": "dashboard.jsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.jsx"
    },
    "/dashboard/facilities": {
      "filePath": "dashboard/facilities.jsx"
    },
    "/dashboard/profile": {
      "filePath": "dashboard/profile.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
